package ca.tyny.urlshortener.infra.adapter.output.persistence.entity;

import ca.tyny.urlshortener.infra.adapter.output.persistence.config.MongoCollections;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Persistence entity mapping a short URL to MongoDB.
 *
 * This class represents the data structure as stored in MongoDB.
 * It should not contain business logic, only data and mapping annotations.
 *
 * Conversion:
 * - Domain Model (ShortUrl) ↔ Mapper ↔ Persistence Entity (ShortUrlEntity)
 */
@Document(collection = MongoCollections.SHORT_URLS)
public class ShortUrlEntity {

    /**
     * Unique identifier for the short URL (primary key).
     * Generated by the domain using Base62 (SecureRandom).
     */
    @Id
    private String id;

    /**
     * Full original URL that was shortened.
     * No unique index — the same URL may be shortened multiple times (no dedup).
     */
    private String originalUrl;

    /**
     * SHA-256 hash of the original URL (lowercase hex).
     * Stored for future analytics; no unique index on this field.
     */
    private String urlHash;

    /**
     * Timestamp of when the URL was shortened.
     */
    private LocalDateTime createdAt;

    @Indexed
    private String userId;

    private boolean isCustomAlias;

    public ShortUrlEntity() {
    }

    /**
     * Constructor with all fields.
     *
     * @param id            unique identifier for the short URL
     * @param originalUrl   original URL to be stored
     * @param urlHash       SHA-256 hash of the original URL
     * @param createdAt     creation timestamp
     * @param userId        ID of the user who created the short URL
     * @param isCustomAlias whether this is a user-supplied vanity alias
     */
    public ShortUrlEntity(String id, String originalUrl, String urlHash, LocalDateTime createdAt, String userId,
            boolean isCustomAlias) {
        this.id = id;
        this.originalUrl = originalUrl;
        this.urlHash = urlHash;
        this.createdAt = createdAt;
        this.userId = userId;
        this.isCustomAlias = isCustomAlias;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    public String getUrlHash() {
        return urlHash;
    }

    public void setUrlHash(String urlHash) {
        this.urlHash = urlHash;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public boolean isCustomAlias() {
        return isCustomAlias;
    }

    public void setCustomAlias(boolean customAlias) {
        isCustomAlias = customAlias;
    }
}
