#!/bin/bash
# MongoDB Backup Script for URL Shortener Service (Epic 8 story 8.5: + manifest contract).
#
# Performs a mongodump of the url_shortener database to a timestamped directory and writes
# a manifest.json alongside the dump: timestamp, db, mongodb version, dump size and the
# ROW COUNTS per collection. The manifest is the restore contract —
# scripts/restore-mongodb.sh --verify re-counts the same collections and fails on any
# divergence ("backup without a verified restore is hope").
#
# Tools note (Epic 8): mongodump/mongosh must be reachable. When the MongoDB Database
# Tools are NOT on the host PATH, the scripts run them in a throwaway mongo:6.0 container
# with --network host (the host-published Mongo port is reachable as-is) and the current
# uid, so dumps land on the host filesystem — the repo's k6/nginx container pattern.
#
# Usage:
#   bash scripts/backup-mongodb.sh [output-dir]
#
# Environment:
#   MONGODB_URI  - MongoDB connection string (default: mongodb://localhost:27017/url_shortener)
#   BACKUP_RETENTION_DAYS - Days to keep backups (default: 30)
#
# Requirements:
#   - mongodump + mongosh in PATH (or the mongo container for the fallback)
#   - Network access to MongoDB

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

MONGODB_URI="${MONGODB_URI:-mongodb://localhost:27017/url_shortener}"
OUTPUT_BASE="${1:-/var/backups/url-shortener}"
RETENTION_DAYS="${BACKUP_RETENTION_DAYS:-30}"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
OUTPUT_DIR="${OUTPUT_BASE}/${TIMESTAMP}"

# Collections whose row counts make up the manifest (every business collection; the
# schema_migrations history is included so the restore can be cross-checked against
# the in-code migrator).
MANIFEST_COLLECTIONS=(short_urls users custom_domains click_events click_daily schema_migrations)

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
die() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*" >&2; exit 1; }

# resolve a mongo CLI tool: PATH first; otherwise generate a wrapper script that runs the
# tool in a throwaway mongo:6.0 container with --network host + the current uid (the repo's
# k6/nginx container pattern from Epics 5-7).
# --network host makes the HOST-published port in MONGODB_URI (e.g. 27018 for an isolated
# stack) reachable directly — no URI rewriting, no docker-exec namespace trap (the exec'd
# tool only sees the container-internal 27017, and its --out would land inside the
# container filesystem, not on the host).
# A wrapper (not a string) is returned so "$MONGODUMP" expands to a single executable word
# in every calling context.
TOOL_BIN_DIR=""
mongo_tool() {
    local bin="$1"
    if command -v "$bin" >/dev/null 2>&1; then
        echo "$bin"
        return 0
    fi
    if docker image inspect mongo:6.0 >/dev/null 2>&1; then
        TOOL_BIN_DIR=$(mktemp -d)
        local wrapper="$TOOL_BIN_DIR/$bin"
        cat > "$wrapper" <<'EOF'
#!/bin/bash
# generated by backup-mongodb.sh/restore-mongodb.sh — runs $bin in a throwaway mongo:6.0
# container. Extra docker args (volume mounts) are appended via MONGO_TOOL_EXTRA_ARGS so the
# caller can mount paths (mongodump --out / mongorestore --dir need host paths).
exec docker run --rm --network host --user "$(id -u):$(id -g)" -e HOME=/tmp \
    ${MONGO_TOOL_EXTRA_ARGS:-} mongo:6.0 "$0exec_bin" "$@"
EOF
        # substitute the tool name into the wrapper (kept simple: the only variable part)
        sed -i "s|\$0exec_bin|$bin|g" "$wrapper"
        chmod +x "$wrapper"
        echo "$wrapper"
        return 0
    fi
    return 1
}
trap '[ -n "${TOOL_BIN_DIR:-}" ] && rm -rf "$TOOL_BIN_DIR"' EXIT

MONGODUMP="$(mongo_tool mongodump)" || die "mongodump not in PATH and mongo:6.0 image unavailable (install MongoDB Database Tools or pull mongo:6.0; see header)"
MONGOSH="$(mongo_tool mongosh)" || die "mongosh not in PATH and mongo:6.0 image unavailable (install MongoDB Database Tools or pull mongo:6.0; see header)"

# Extract database name from URI
DB_NAME=$(echo "$MONGODB_URI" | sed -E 's|.*/([^/?]+)(\?.*)?$|\1|')
if [ -z "$DB_NAME" ]; then
    DB_NAME="url_shortener"
fi

log "Starting MongoDB backup for database: $DB_NAME"
log "Output directory: $OUTPUT_DIR"

mkdir -p "$OUTPUT_DIR"

# mongo version for the manifest (best-effort)
MONGO_VERSION="$($MONGOSH "$MONGODB_URI" --quiet --eval 'db.version()' 2>/dev/null || echo unknown)"

# Perform backup. When the tool is the generated container wrapper, mount a temp host dir
# at /mongodump-out so the dump lands on the host filesystem (MONGO_TOOL_EXTRA_ARGS is read
# by the wrapper). NOTE: the wrapper path is an absolute mktemp path under /tmp — that is
# how we detect it (command substitution runs mongo_tool in a subshell, so TOOL_BIN_DIR is
# not visible here; content-sniffing the path is the deterministic check).
DUMP_OUT="$OUTPUT_DIR"
DUMP_VOL=""
case "$MONGODUMP" in
    /tmp/tmp.*/mongodump)
        DUMP_VOL=$(mktemp -d)
        DUMP_OUT=/mongodump-out
        export MONGO_TOOL_EXTRA_ARGS="-v $DUMP_VOL:/mongodump-out"
        ;;
esac

if $MONGODUMP --uri="$MONGODB_URI" --db="$DB_NAME" --out="$DUMP_OUT" --gzip; then
    if [ -n "$DUMP_VOL" ]; then
        mv "$DUMP_VOL"/* "$OUTPUT_DIR"/
        rmdir "$DUMP_VOL" 2>/dev/null || true
    fi
    log "Backup completed successfully: $OUTPUT_DIR"

    if [ ! -d "$OUTPUT_DIR/$DB_NAME" ]; then
        log "ERROR: Backup directory structure unexpected — mongodump exited 0 but produced NO '$DB_NAME' directory. mongodump exits 0 SILENTLY when the database does not exist at the target URI; check MONGODB_URI points at the intended instance (and that the app/stack actually created data there)."
        exit 1
    fi
    COLLECTION_COUNT=$(find "$OUTPUT_DIR/$DB_NAME" -name "*.bson.gz" | wc -l)
    log "Backup contains $COLLECTION_COUNT collections"
else
    log "ERROR: mongodump failed"
    rm -rf "$OUTPUT_DIR"
    exit 1
fi

# ---------------------------------------------------------------- manifest (Epic 8 story 8.5)
# Row counts per collection via mongosh countDocuments — the restore --verify contract.
MANIFEST="$OUTPUT_DIR/manifest.json"
log "Writing manifest: $MANIFEST"
{
    echo '{'
    echo "  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\","
    echo "  \"database\": \"$DB_NAME\","
    echo "  \"mongodb_version\": \"$MONGO_VERSION\","
    echo "  \"dump_size_bytes\": $(du -sb "$OUTPUT_DIR" | cut -f1),"
    echo "  \"collections\": {"
    first=true
    for c in "${MANIFEST_COLLECTIONS[@]}"; do
        count=$($MONGOSH "$MONGODB_URI" --quiet --eval "db.$c.countDocuments({})" 2>/dev/null || echo 0)
        if $first; then first=false; else echo ","; fi
        printf '    "%s": %s' "$c" "$count"
    done
    echo ""
    echo "  }"
    echo '}'
} > "$MANIFEST"
log "Manifest written: $MANIFEST ($(tr -d '\n ' < "$MANIFEST" | head -c 200)…)"

# Cleanup old backups (30d rotation preserved)
log "Cleaning up backups older than $RETENTION_DAYS days..."
find "$OUTPUT_BASE" -maxdepth 1 -type d -name "20*" -mtime +"$RETENTION_DAYS" -exec rm -rf {} \; 2>/dev/null || true

REMAINING=$(find "$OUTPUT_BASE" -maxdepth 1 -type d -name "20*" | wc -l)
log "Backup complete. $REMAINING backups retained in $OUTPUT_BASE"
